<FORM name="agp" method="POST" action="<?php echo BASE . 'gerencia/lista-projeto/' ;  ?>" enctype="multipart/form-data">
  <?php echo (isset($this->alert) ? $this->alert : '');?>

  <aside class="container">
    

        <font size="6">
          <br>
         
            <div class="panel-body">
              <font size="5"> 
               <center><b><p>Escolha a granularidade</p></b></center>
             </font>
             <br>
             <center>
               <div class="col-md-4">
               </div>
               <div class="col-md-4">
                 <div class="input-group date" data-provide="datepicker">
                 <input class="form-control" id="datepicker" type="text" placeholder="MM/DD/AAAA" maxlength="10" name="dataInicio"/>
                   <div class="input-group-addon">
                    <span class="glyphicon glyphicon-th"></span>
                  </div>
                </div> 

                <br>
                
                <div class="input-group date" data-provide="datepicker">
                  <input type="text" class="form-control" placeholder="MM/DD/AAAA" maxlength="10" name="dataFim">
                  <div class="input-group-addon">
                    <span class="glyphicon glyphicon-th"></span>
                  </div>
                </div>
                <br>
                <br>
                <input type="submit" class="btn btn-default cor-botao" value="    OK   " >

              </center>
            </font>
            <br>
          </div>

        </div>
      </div>
    </div>
  </div>
</aside>
</section>
</FORM>
</body>
</html>