<?php echo (isset($this->alert) ? $this->alert : '');?>

<FORM name="agp" method="POST" action="<?php echo BASE;  ?>docente/pesquisa-membros" enctype="multipart/form-data">
  <div class="container-fluid">
    <br>
    <br>
    <div class="container col-sm-8">
      <div class="text-center">
        <h1 class="h3 mb-2 font-weight-normal">Membros do grupo</h1>
        <br>
        <div class="input-group mb-3">
          <input type="text" class="form-control" required placeholder="Pesquisar membro: " name="barra" aria-label="" aria-describedby="button-addon1">
          <div class="input-group-append">
            <input class="btn btn-info" type="submit" data-toggle="modal" data-target="#erroMensagemMensagem" id="button-addon2" value="Pesquisar">
          </div>
        </div>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Usuário:</th>
          <th scope="col">Nome:</th>
          <th scope="col">Nível:</th>
          <th scope="col">Excluir:</th>
        </tr>
      </thead>
      <tbody>
        <?php 
        foreach ($view_lista as $l) {
          $usuario = User::find($l->users_id);
          ?>
          <tr>
            <td><?php echo $usuario->login; ?></td>
            <td><?php echo $usuario->name; ?></td>
            <td><?php echo Schooling::find($usuario->schoolings_id)->description; ?></td>
            <td><a href="<?php echo BASE.'docente/excluir-membro/'.$usuario->id; ?>"><span class="badge badge-info" data-toggle="modal" data-target="#exclusaoMensagem">Excluir</span></a></td>
          </tr>
          <?php
        } 
        ?>     
      </tbody>
    </table>
    <br>
    <br>
    <br>
    <br>
    <div class="text-center">
      <a class="nav-link active" href="<?php echo BASE.'docente/menu-grupo'; ?>"><button type="button" class="btn btn-info">Voltar</button></a>
    </div>
    <nav class="navbar fixed-bottom navbar-light">
      <a href="#bannerformmodal" data-toggle="modal" data-target="#ajuda">Ajuda</a>
    </nav>
  </div>
  <!--
MENSAGEM DE AJUDA MEMBROS DO GRUPO
-->
<div class="modal" tabindex="-1" id="ajuda" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajuda</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Essa é a lista com os membros do seu grupo</p>
        <br>
        <p>Você pode consultar a lista ou pesquisar algum membro pelo nome do usuário, basta digitar o nome do usuario no campo e clicar em Pesquisar.</p>
        <br>
        <p>Você também pode excluir algum membro, basta clicar no Excluír referente ao membro no qual você deseja retirar do grupo.</p>
        <br>
        <p>Caso queira desistir clique no botão Voltar.</p>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-dismiss="modal">Ok</button>
        </div>
      </div>
    </div>
  </div>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </html>