<?php echo (isset($this->alert) ? $this->alert : '');?>
<body>
  <div class="container-fluid">
    <br>
    <br>
    <div class="text-center">
      <h1 class="h3 mb-2 font-weight-normal">Provas</h1>
      <br>
      <a class="nav-link active" href="<?php echo BASE . 'docente/cadastrar-prova'; ?>"><button type="button" class="btn btn-info">Cadastro de Provas</button></a>
      </div>
      <br>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Ativa?</th>
            <th scope="col">Nível Educacional:</th>
            <th scope="col">Número de Questões:</th>
            <th scope="col">Opções:</th>
          </tr>
        </thead>
        <tbody>
          <?php 
          foreach ($view_prova as $p) {
            if($p->status != 2){
              ?>
              <tr>
                <td>
                  <?php 
                    if($p->status == 0) echo 'Não';
                    else echo 'Sim';     
                  ?>
                </td>
                <td>
                  <?php 
                    if($p->schoolings_id == 1) echo 'Fundamental';
                    else if($p->schoolings_id == 2) echo 'Médio';
                    else if($p->schooling_id ==3) echo 'Superior';
                  ?>
                </td>
                
                <td>10</td>
                <td>
                  <?php 
                    echo $p->description;                    
                  ?>
                </td>
                <td>
                  <a href="<?php echo BASE. 'docente/ativa-prova/'. $p->id;?>"><span class="badge badge-info" data-toggle="modal" data-target="#ativarProva">Ativar</span></a>
                  <a href="<?php echo BASE. 'docente/alterar-prova/'.$p->id. '/'. $p->schoolings_id;?>"><span class="badge badge-info">Alterar</span></a>
                  <a href="<?php echo BASE. 'docente/excluir-prova/'.$p->id;?>"><span class="badge badge-info" data-toggle="modal" data-target="#exclusaoMensagem">Excluir</span></a>
                </td>
              </tr>   
              <?php 
            } 
          }
          ?>    
        </tbody>
      </table>
      <br>
      <br>
      <div class="text-center">
        <a class="nav-link active" href="<?php echo BASE . 'docente/menu-prova'; ?>"><button type="button" class="btn btn-info">Voltar</button></a>
      </div>
    </div>
  </body>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </html>