<html>
<FORM name="agp" method="POST" action="<?php echo BASE . 'gerencia/pesquisa-funcionario/' ;  ?>" enctype="multipart/form-data">
  <body>
   <?php echo (isset($this->alert) ? $this->alert : '');?>
   <section>

    <aside class="container">
      <br>
      <div class="panel-body">
        <font size="6">
          <center><b><p>Funcionários Alocados</p></b></center>
          
          <center><b><p>Projeto <?php echo $view_projeto;?></p></b></center>
        </font>
        <br>
        <br>
        <br>
        <div id="list" class="row">
          <div class="table-responsive col-md-12">
            <table class="table" cellspacing="0" cellpadding="0">
              <thead>
                <?php if(isset($view_func) and is_array($view_func) and !is_null($view_func)){ ?>
                  <tr>
                    <th>Cod</th>
                    <th>Nome</th>
                    <th>Cargo</th>
                    
                  </tr>
                </thead>
                <tbody>
                  <?php 
                  $i = 0;

                  foreach ($view_func as $f) {

                    $func = Contributor::find($view_func[$i]->contributor_id); 
                    $r = Role::find($func->role_id);                 
                    ?>
                    <tr>
                      <td><?php echo $view_func[$i]->contributor_id; ?></td>
                      <td><?php echo $func->name; ?></td>
                      <td><?php echo $r->description; ?></td>  

                    </tr>
                    <?php $i = $i + 1;}
                  }
                  elseif(isset($view_func) and !is_null($view_func)){?>
                   <tr>
                    <th>Cod</th>
                    <th>Nome</th>
                    <th>Cargo</th>

                  </tr>
                </thead>
                <tbody>
                  <?php 
                  $i = 0;

                  foreach ($view_func as $f) {
                    $func = Contributor::find($view_func->contributor_id); 
                   $r = Role::find($func->role_id);                   
                   ?>
                   <tr>
                    <td><?php echo $view_func->contributor_id; ?></td>
                    <td><?php echo $func->name; ?></td>
                    <td><?php echo $r->description; ?></td>             
                  </tr>
                  <?php $i = $i + 1;}

                }
                else{ ?>
                  <tbody>
                    <thead>
                      <tr>
                        <th>Cod</th>
                        <th>Nome</th>
                        <th>Cargo</th>
                        <th></th>
                      </tr>
                    </thead>
                  </tbody>
                <?php } ?>
              </table>
            </div>
          </div>
        </aside>
      </section>
    </form>
  </body>
  </html>