 <?php echo (isset($this->alert) ? $this->alert : '');?>

<!--
CORPO DA PAGINA
-->
<div class="container-fluid">
  <br>
  <br>
  <div class="text-center">
    <h1 class="h3 mb-2 font-weight-normal">Perguntas</h1>
    <br>
    <a class="nav-link active" href="<?php echo BASE. 'docente/cadastrar-pergunta'; ?>"><button type="button" class="btn btn-info">Cadastro de Perguntas</button></a>
    <br>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nível:</th>
        <th scope="col">Disciplina:</th>
        <th scope="col">Pergunta:</th>
        <th scope="col">Opções:</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($view_questoes as $q) {

        $nivel = Schooling::find($q->schoolings_id);

        $disciplina = Discipline::find($q->disciplines_id);
        echo '<tr>';
        echo '<td>'. $nivel->description .'</td>';
        echo '<td>'. $disciplina->description .'</td>';
        echo '<td>'. substr($q->question, 0, 20) .'</td>';
        echo '<td><a href="' . BASE . 'docente/alterar-pergunta/'. $q->id .'"><span class="badge badge-info">Alterar</span></a> ';
                //echo '<a href="' . BASE . 'docente/excluir-pergunta/'. $q->id .'"><span class="badge badge-info" data-toggle="modal" data-target="#exclusaoMensagem">Excluir</span></a>';
        echo '<span class="badge badge-info" data-toggle="modal" data-target="#exclusaoMensagem">Excluir</span></td></tr>';
      } ?>      
    </tbody>
  </table>
  <br>
  <br>
  <div class="text-center">
    <a class="nav-link active" href="<?php echo BASE. 'docente/menu-prova'; ?>"><button type="button" class="btn btn-info">Voltar</button></a>
  </div>
  <nav class="navbar fixed-bottom navbar-light">
    <a href="#bannerformmodal" data-toggle="modal" data-target="#ajuda">Ajuda</a>
  </nav>
</div>

</body>

<!--
MENSAGEM DE AJUDA TELA PERGUNTAS
-->
<div class="modal" tabindex="-1" id="ajuda" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajuda</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Essa é a lista com as perguntas cadastradas no sistema.</p>
        <br>
        <p>Você pode adicionar novas perguntas, basta clicar em Cadastro de perguntas.</p>
        <br>
        <p>Você também pode alterar ou excluir alguma pergunta, basta clicar no botão Alterar ou Excluír referente a pergunta exibida na lista.</p>
        <br>
        <p>Para exluír uma pergunta é necessario confirmar a mensagem de exclusão.</p>
        <br>
        <p>Caso queira desistir clique no botão Voltar.</p>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-dismiss="modal">Ok</button>
        </div>
      </div>
    </div>
  </div>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </html>