
<?php echo (isset($this->alert) ? $this->alert : '');?>
<FORM name="agp" method="POST" action="<?php echo BASE;  ?>docente/adicionar-usuario" enctype="multipart/form-data">


  <body>

   <div class="container-fluid">
    <div class="container col-sm-8">
      <br>
      <br>
      <ul class="nav nav-pills nav-fill">
        <li class="nav-item">
          <a class="nav-link link-pagina" href="<?php echo BASE . 'docente/menu-prova' ?>">Provas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-pagina" href="<?php echo BASE . 'docente/menu-grupo' ?>">Grupo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-pagina" href="<?php echo BASE . 'docente/menu-status' ?>">Status</a>
        </li>
      </ul>
      <div class="text-center">
        <br>
        <br>
        <h1 class="h3 mb-2 font-weight-normal">Grupo</h1>
      </div>
      <h1 class="h6 mb-2 font-weight-normal">Adicionar no grupo:</h1>
      <div class="input-group mb-3">
        <input required type="text" <?php if(isset($view_post)) echo 'value="'.$view_post.'"'; ?> class="form-control"  name="usuario" aria-label="" aria-describedby="basic-addon1">
        <div class="input-group-append">
          <input class="btn btn-info" type="submit" data-toggle="modal" value="Enviar">
        </div>
      </div>
      <br>
      <br>
      <br>
      <div class="text-center">
        <a class="nav-link active" href="<?php echo BASE.'docente/lista-membros' ?>"><button type="button" class="btn btn-info"> Membros do grupo</button></a>
      </div>
    </div>
    <nav class="navbar fixed-bottom navbar-light">
      <a href="#bannerformmodal" data-toggle="modal" data-target="#ajuda">Ajuda</a>
    </nav>
  </div>
</body>
<!--
PARTE DO ADMINISTRADOR
-->

<!--
MENSAGEM DE AJUDA DASHBOARD DO ADMINISTRADOR
-->
<div class="modal" tabindex="-1" id="ajuda" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajuda</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Essa é a lista dos membros presente no seu grupo. Aqui você pode:</p>
        <p>Pesquisar algum membro.</p>
        <br>
        <p>Alterar seus dados cadastrados.</p>
        <br>
        <p>Adicionar, excluír ou consultar os membro do seu grupo.</p>
        <br>
        <p>Cadastrar, editar ou excluír suas perguntas.</p>
        <br>
        <p>Cadastrar, editar, excluír ou ativar suas provas.</p>
        <p>Para realizar essas ações basta navegar pelas abas disponíveis na tela.</p>
        <p>Caso você deseje sair, clique na opção Sair presente na barra superior.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>