<html lang="pt-br">
<header>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $view_title; ?></title>

    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/css/bootstrap.min.css" type="text/css">

    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">  
    <link rel="stylesheet" href="<?php echo CSS; ?>cores.css" type="text/css">
    <script src="<?php echo BOWER; ?>bootstrap/js/jquery.js"></script>
    <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap.min.js"></script>
    <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap-datepicker.js"></script>
    <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap-datepicker.min.js"></script>
    <script src="<?php echo BOWER; ?>bootstrap/locales/bootstrap-datepicker.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="<?php echo BOWER. 'jquery/src/game.js'; ?>"></script>


    <?php 
    echo $add_css;
    echo $add_js

    ?>
    <title>Batalha Naval - Dashboard</title>
    <link rel="icon" href="<?php echo IMG ?>icon.ico">
    <link rel="stylesheet" type="text/css" href="css/cores.css">
  </head>

  <body>
<!--
BARRA SUPERIOR
-->
<nav class="navbar cor-barra">
  <a class="navbar-brand" href="<?php echo BASE. 'aluno/menu-jogo' ?>"><img class="img-responsive" src="<?php echo IMG; ?>logo.png" alt="LOGO" width="165" height="72"></a>
  <div class="col-md-2 row">
    <?php
                //if(isset($this->auth->getUserId()))
    $teste = $this->auth->getUserId();  
    if(!is_null($teste)){
      $user = User::find($teste);
      echo '<div class="col-md-2 row">';
      echo '<a class="nav-link barra-link" href="'.BASE.'aluno/menu-jogo">Olá, '.$user->name.'</a>';
      echo '<a class="nav-link barra-link" href="'.BASE.'login/sair">Sair</a>';
    }


    unset($teste);
    ?>
  </div>
</nav>



<FORM name="agp" method="POST" action="<?php echo BASE . 'login/redefinir/'. $view_id;  ?>" enctype="multipart/form-data">

  <?php echo (isset($this->alert) ? $this->alert : '')?>
  <aside class="container" style="margin-top:100px;">

    <center>
      <div class="col-md-12">
        <div class="panel-body">
          <center>
            <h1 class="h3 mb-2 font-weight-normal">Redefinir Senha</h1>
            <br>
          </center>
          <br>
          <div class="col-md-2">
          </div>
          <div class="col-md-5">
            <label for="inputSenha"><h3 class="h6 mb-2 font-weight-normal">Digite sua senha: </h3></label>
            <input  required class="form-control" id="inputSenha" maxlength="30" type="password" name="password" placeholder="Digite a sua Senha" />
            <br>
            <label for="inputSenha2"><h3 class="h6 mb-2 font-weight-normal">Digite sua senha novamente: </h3></label>
            <input required  class="form-control" id="inputSenha2" type="password" maxlength="30" name="confirmpassword" placeholder="Digite sua senha novamente" />
            <br>
            <br>
            <br>
            <br>
            <br>

            <center>
              <button type="button" class="btn btn-info" data-dismiss="modal">Redefinir</button>
            </center>
            </div>

          </div>
        </div>
      </div>
    </aside>




    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="js/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual
          files as needed -->
          <script src="js/bootstrap.min.js"></script>

        </center>
      </aside>

    </article>

  </section>

</FORM>
</body>
</html>
