<?php echo (isset($this->alert) ? $this->alert : '');?>
<div class="container-fluid">
  <div class="container col-sm-8">
    <br>
    <br>
    <ul class="nav nav-pills nav-fill">
      <li class="nav-item">
        <a class="nav-link link-pagina" href="<?php echo BASE. 'aluno/menu-jogo'; ?>">Jogo</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-pagina" href="<?php echo BASE. 'aluno/menu-status'; ?>">Status</a>
      </li>
    </ul>
    <div class="text-center">
      <br>
      <br>
      <h1 class="h3 mb-2 font-weight-normal">Status</h1>
    </div>
    <?php 
    $partidas = count(Group::find_all_by_users_id($this->auth->getUserId()));
    $desistencia = count(Group::find_all_by_users_id_and_pontuacao($this->auth->getUserId(), 0));
    ?>
    <h1 class="h6 mb-2 font-weight-normal">Número de partidas: <?php echo $partidas;?></h1>
    <h1 class="h6 mb-2 font-weight-normal">Número de partidas concluídas: <?php echo $partidas - $desistencia; ?></h1>
    <h1 class="h6 mb-2 font-weight-normal">Porcentagem de partidas concluídas: <?php echo (($partidas>0) ? round((($partidas - $desistencia)/$partidas)*100). '%': '-');?></h1>
    <h1 class="h6 mb-2 font-weight-normal">Nível Educacional: <?php echo Schooling::find(User::find($this->auth->getUserId())->schoolings_id)->description; ?></h1>
    <div class="text-center">
      <br>
      <br>
      <a class="nav-link active" href="<?php echo BASE.'aluno/alterar-usuario' ?>"><button type="button" class="btn btn-info"> Alterar dados</button></a>
    </div>
  </div>
  <nav class="navbar fixed-bottom navbar-light">
    <a href="#bannerformmodal" data-toggle="modal" data-target="#ajuda">Ajuda</a>
  </nav>
</div>
</body>
<!--
MENSAGEM DE AJUDA DASHBOARD DO USUARIO
-->
<div class="modal" tabindex="-1" id="ajuda" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajuda</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Aqui é sua dashboard, neste local você pode:</p>
        Consultar seu status.
        <br>
        Alterar seus dados cadastrados.
        <br>
        Consultar o ranking de seu grupo.
        <br>
        Realizar suas provas.
        <br>
        Jogar batalha naval.
        <p>Para realizar essas ações basta navegar pelas abas disponíveis na tela.</p>
        <p>Caso você deseje sair, clique na opção Sair presente na barra superior.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>