<?php echo (isset($this->alert) ? $this->alert : '');?>
<div class="container-fluid">
  <div class="container col-sm-8">
    <br>
    <br>
    <ul class="nav nav-pills nav-fill">
      <li class="nav-item">
        <a class="nav-link link-pagina" href="<?php echo BASE. 'aluno/menu-jogo'; ?>">Jogo</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-pagina" href="<?php echo BASE. 'aluno/menu-status'; ?>">Status</a>
      </li>
    </ul>
    <div class="text-center">
      <br>
      <br>
      <h1 class="h3 mb-2 font-weight-normal">Jogo</h1>
    </div>
    <h1 class="h6 mb-2 font-weight-normal">Admistrador: 
      <?php 
      if(GroupUser::find_by_users_id($this->auth->getUserId())){
        echo User::find(GroupUser::find_by_users_id($this->auth->getUserId())->admin_id)->name; 
        echo '</h1>';

        echo '<a class="link-pagina" href="'. BASE. 'aluno/ranking-grupo">Ranking do grupo</a>';
      }
      else{
        echo "";
        echo '<br>';
      }
      ?>


      <br>
      <br>
      <br>
      <br>
      <br>
      <div class="text-center">
        <a class="nav-link active" href="<?php echo BASE.'aluno/prova-jogo'; ?>">
          <button
          <?php 
          if (is_null(GroupUser::find_by_users_id($this->auth->getUserId()))){
            echo "disabled";

          } 
          else{
            if(is_null(Test::find_by_schoolings_id_and_status_and_users_id($this->auth->getUserRole(), 1, GroupUser::find_by_users_id($this->auth->getUserId())->admin_id))){
              echo 'disabled';
            } 
          }

          ?>

          type="button" class="btn btn-info">Jogar</button></a>
          <a class="nav-link active" href="<?php echo BASE.'aluno/prova'; ?>">
            <button
            <?php 
            if (is_null(GroupUser::find_by_users_id($this->auth->getUserId()))){
              echo "disabled";

            } 
            else{
              if(is_null(Test::find_by_schoolings_id_and_status_and_users_id($this->auth->getUserRole(), 1, GroupUser::find_by_users_id($this->auth->getUserId())->admin_id))){
                echo 'disabled';
              } 
            }

            ?>
            type="button" class="btn btn-info">Realizar Prova</button></a>
          </div>
        </div>

          <nav class="navbar fixed-bottom navbar-light">
            <a href="#bannerformmodal" data-toggle="modal" data-target="#ajuda">Ajuda</a></nav></h1>
          </nav>
      </div>
      <!--
MENSAGEM DE AJUDA DASHBOARD DO USUARIO
-->
 <div class="modal" tabindex="-1" id="ajuda" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajuda</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Aqui é sua dashboard, neste local você pode:</p>
        Consultar seu status.
        <br>
        Alterar seus dados cadastrados.
        <br>
        Consultar o ranking de seu grupo.
        <br>
        Realizar suas provas.
        <br>
        Jogar batalha naval.
        <p>Para realizar essas ações basta navegar pelas abas disponíveis na tela.</p>
        <p>Caso você deseje sair, clique na opção Sair presente na barra superior.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      </html>

      <!DOCTYPE html>
      <html lang="pt-br">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">



        <link href="http://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/skeleton.css">
        <link rel="stylesheet" href="css/game.css">
        <link rel="icon" type="image/png" href="images/favicon.png">
      </head>


      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
      <script src="js/game.js"></script>

      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "http://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.5";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
    </body>
    </html>
